apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jyvl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jyvl
    app.kubernetes.io/part-of: my-app2
  name: devfile-sample-jyvl
  namespace: eyuen-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-jyvl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-jyvl
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:79197095c2def1740faa7141c7e034d1e22d98e622b9b3eb90b69edb17380656
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
